// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOAJPpQOWRlGrZYa4QYy0V3vpAvdCUMBA',
    appId: '1:985503737164:web:13538ae5bd2b5cbc7c5be9',
    messagingSenderId: '985503737164',
    projectId: 'sunsetmarketplace',
    authDomain: 'sunsetmarketplace.firebaseapp.com',
    databaseURL: 'https://sunsetmarketplace-default-rtdb.firebaseio.com',
    storageBucket: 'sunsetmarketplace.firebasestorage.app',
    measurementId: 'G-KL1TF64MK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbyTb3UVNWQp7I0bGdCFQ9OnywbWUNx-g',
    appId: '1:985503737164:android:e098e4ace00370cc7c5be9',
    messagingSenderId: '985503737164',
    projectId: 'sunsetmarketplace',
    databaseURL: 'https://sunsetmarketplace-default-rtdb.firebaseio.com',
    storageBucket: 'sunsetmarketplace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVpZfRf3_BNKzAElfaLjEKAxNSB1Sv350',
    appId: '1:985503737164:ios:7d54633f016718427c5be9',
    messagingSenderId: '985503737164',
    projectId: 'sunsetmarketplace',
    databaseURL: 'https://sunsetmarketplace-default-rtdb.firebaseio.com',
    storageBucket: 'sunsetmarketplace.firebasestorage.app',
    iosBundleId: 'com.example.sunset',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVpZfRf3_BNKzAElfaLjEKAxNSB1Sv350',
    appId: '1:985503737164:ios:7d54633f016718427c5be9',
    messagingSenderId: '985503737164',
    projectId: 'sunsetmarketplace',
    databaseURL: 'https://sunsetmarketplace-default-rtdb.firebaseio.com',
    storageBucket: 'sunsetmarketplace.firebasestorage.app',
    iosBundleId: 'com.example.sunset',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOAJPpQOWRlGrZYa4QYy0V3vpAvdCUMBA',
    appId: '1:985503737164:web:13538ae5bd2b5cbc7c5be9',
    messagingSenderId: '985503737164',
    projectId: 'sunsetmarketplace',
    authDomain: 'sunsetmarketplace.firebaseapp.com',
    databaseURL: 'https://sunsetmarketplace-default-rtdb.firebaseio.com',
    storageBucket: 'sunsetmarketplace.firebasestorage.app',
    measurementId: 'G-KL1TF64MK3',
  );
}
